export const camisetaModelos = [
  {
    id: 1,
    tipo: 'hombre',
    nombre: 'Ondine',
    url: '/assets/images/modelos/Ondine.png',
    urlSvg: 'Ondine.svg',
    urlZoom: '/assets/images/zoom/Ondine.png',
    precioIndividual: 1590,
    precioMayorista: 1190,
    seleccionada: false,
    visible: false,
  },
  {
    id: 2,
    tipo: 'hombre',
    nombre: 'Borussia',
    url: '/assets/images/modelos/Borussia.png',
    urlSvg: 'Borussia.svg',
    urlZoom: '/assets/images/zoom/Borussia.png',
    precioIndividual: 1990,
    precioMayorista: 1490,
    seleccionada: false,
    visible: false,
  },
  {
    id: 3,
    tipo: 'hombre',
    nombre: 'Juve',
    url: '/assets/images/modelos/Juve.png',
    urlSvg: 'Juve.svg',
    urlZoom: '/assets/images/zoom/Juve.png',
    precioIndividual: 1990,
    precioMayorista: 1490,
    seleccionada: false,
    visible: false,
  },
  {
    id: 4,
    tipo: 'hombre',
    nombre: 'City',
    url: '/assets/images/modelos/City.png',
    urlSvg: 'City.svg',
    urlZoom: '/assets/images/zoom/City.png',
    precioIndividual: 1990,
    precioMayorista: 1490,
    seleccionada: false,
    visible: false,
  },
  {
    id: 5,
    tipo: 'hombre',
    nombre: 'Inter',
    url: '/assets/images/modelos/Inter.png',
    urlSvg: 'Inter.svg',
    urlZoom: '/assets/images/zoom/Inter.png',
    precioIndividual: 1990,
    precioMayorista: 1490,
    seleccionada: false,
    visible: false,
  },
  {
    id: 6,
    tipo: 'hombre',
    nombre: 'Dortmund',
    url: '/assets/images/modelos/Dortmund.png',
    urlSvg: 'Dortmund.svg',
    urlZoom: '/assets/images/zoom/Dortmund.png',
    precioIndividual: 1990,
    precioMayorista: 1490,
    seleccionada: false,
    visible: false,
  },
  {
    id: 7,
    tipo: 'hombre',
    nombre: 'Master',
    url: '/assets/images/modelos/Master.png',
    urlSvg: 'Master.svg',
    urlZoom: '/assets/images/zoom/Master.png',
    precioIndividual: 1350,
    precioMayorista: 990,
    seleccionada: false,
    visible: false,
  },
  {
    id: 8,
    tipo: 'hombre',
    nombre: 'United',
    url: '/assets/images/modelos/United.png',
    urlSvg: 'United.svg',
    urlZoom: '/assets/images/zoom/United.png',
    precioIndividual: 1990,
    precioMayorista: 1490,
    seleccionada: false,
    visible: false,
  },
  // {
  //   id: 9,
  //   tipo: 'hombre',
  //   nombre: 'Rivera',
  //   url: '/assets/images/modelos/Rivera.png',
  //   urlSvg: 'Rivera.svg',
  //   urlZoom: '/assets/images/zoom/Rivera.svg',
  //   precioIndividual: 1590,
  //   precioMayorista: 1190,
  //   seleccionada: false,
  //   visible: false,
  // },
  // {
  //   id: 10,
  //   tipo: 'hombre',
  //   nombre: 'Millo',
  //   url: '/assets/images/modelos/Millo.png',
  //   urlSvg: 'Millo.svg',
  //   urlZoom: '/assets/images/zoom/Millo.svg',
  //   precioIndividual: 1990,
  //   precioMayorista: 1490,
  //   seleccionada: false,
  //   visible: false,
  // },
  // {
  //   id: 11,
  //   tipo: 'hombre',
  //   nombre: 'Matador',
  //   url: '/assets/images/modelos/Matador.png',
  //   urlSvg: 'Matador.svg',
  //   urlZoom: '/assets/images/zoom/Matador.svg',
  //   precioIndividual: 1990,
  //   precioMayorista: 1490,
  //   seleccionada: false,
  //   visible: false,
  // },
  // {
  //   id: 12,
  //   tipo: 'hombre',
  //   nombre: 'Pirata',
  //   url: '/assets/images/modelos/Pirata.png',
  //   urlSvg: 'Pirata.svg',
  //   urlZoom: '/assets/images/zoom/Pirata.svg',
  //   precioIndividual: 1990,
  //   precioMayorista: 1490,
  //   seleccionada: false,
  //   visible: false,
  // },
  // {
  //   id: 13,
  //   tipo: 'hombre',
  //   nombre: 'Argento',
  //   url: '/assets/images/modelos/Argento.png',
  //   urlSvg: 'Argento.svg',
  //   urlZoom: '/assets/images/zoom/Argento.svg',
  //   precioIndividual: 1990,
  //   precioMayorista: 1490,
  //   seleccionada: false,
  //   visible: false,
  // },
  // {
  //   id: 14,
  //   tipo: 'hombre',
  //   nombre: 'Vecort',
  //   url: '/assets/images/modelos/Vecort.png',
  //   urlSvg: 'Vecort.svg',
  //   urlZoom: '/assets/images/zoom/Vecort.svg',
  //   precioIndividual: 1590,
  //   precioMayorista: 1190,
  //   seleccionada: false,
  //   visible: false,
  // },
  // {
  //   id: 15,
  //   tipo: 'hombre',
  //   nombre: 'Verline',
  //   url: '/assets/images/modelos/Verline.png',
  //   urlSvg: 'Verline.svg',
  //   urlZoom: '/assets/images/zoom/Verline.svg',
  //   precioIndividual: 1590,
  //   precioMayorista: 1190,
  //   seleccionada: false,
  //   visible: false,
  // },
  // {
  //   id: 16,
  //   tipo: 'hombre',
  //   nombre: 'Classic',
  //   url: '/assets/images/modelos/Classic.png',
  //   urlSvg: 'Classic.svg',
  //   urlZoom: '/assets/images/zoom/Classic.svg',
  //   precioIndividual: 1590,
  //   precioMayorista: 1190,
  //   seleccionada: false,
  //   visible: false,
  // },
  // {
  //   id: 17,
  //   tipo: 'hombre',
  //   nombre: 'Lepra',
  //   url: '/assets/images/modelos/Lepra.png',
  //   urlSvg: 'Lepra.svg',
  //   urlZoom: '/assets/images/zoom/Lepra.svg',
  //   precioIndividual: 1590,
  //   precioMayorista: 1190,
  //   seleccionada: false,
  //   visible: false,
  // },
  // {
  //   id: 18,
  //   tipo: 'hombre',
  //   nombre: 'Duline',
  //   url: '/assets/images/modelos/Duline.png',
  //   urlSvg: 'Duline.svg',
  //   urlZoom: '/assets/images/zoom/Duline.svg',
  //   precioIndividual: 1590,
  //   precioMayorista: 1190,
  //   seleccionada: false,
  //   visible: false,
  // },
  // {
  //   id: 19,
  //   tipo: 'hombre',
  //   nombre: 'Trilo',
  //   url: '/assets/images/modelos/Trilo.png',
  //   urlSvg: 'Trilo.svg',
  //   urlZoom: '/assets/images/zoom/Trilo.svg',
  //   precioIndividual: 1590,
  //   precioMayorista: 1190,
  //   seleccionada: false,
  //   visible: false,
  // },
  // {
  //   id: 20,
  //   tipo: 'hombre',
  //   nombre: 'Dynamo',
  //   url: '/assets/images/modelos/Dynamo.png',
  //   urlSvg: 'Dynamo.svg',
  //   urlZoom: '/assets/images/zoom/Dynamo.svg',
  //   precioIndividual: 1990,
  //   precioMayorista: 1490,
  //   seleccionada: false,
  //   visible: false,
  // },
  // {
  //   id: 21,
  //   tipo: 'hombre',
  //   nombre: 'Albo',
  //   url: '/assets/images/modelos/Albo.png',
  //   urlSvg: 'Albo.svg',
  //   urlZoom: '/assets/images/zoom/Albo.svg',
  //   precioIndividual: 1590,
  //   precioMayorista: 1190,
  //   seleccionada: false,
  //   visible: false,
  // },
  // {
  //   id: 22,
  //   tipo: 'hombre',
  //   nombre: "Pixel",
  //   url: '/assets/images/modelos/Pixel.png',
  //   urlSvg: 'Pixel.svg',
  //   urlZoom: '/assets/images/zoom/Pixel.svg',
  //   precioIndividual: 1590,
  //   precioMayorista: 1190,
  //   seleccionada: false,
  //   visible: false,
  // },
  //MODELOS DE MUJER
  {
    id: 23,
    tipo: 'mujer',
    nombre: 'Pyramid',
    url: '/assets/images/modelos/Pyramid.png',
    urlSvg: 'Pyramid.svg',
    urlZoom: '/assets/images/zoom/Pyramid.svg',
    precioIndividual: 1590,
    precioMayorista: 1190,
    seleccionada: false,
    visible: false,
  },
  {
    id: 24,
    tipo: 'mujer',
    nombre: 'Chelsea',
    url: '/assets/images/modelos/Chelsea.png',
    urlSvg: 'Chelsea.svg',
    urlZoom: '/assets/images/zoom/Chelsea.svg',
    precioIndividual: 1990,
    precioMayorista: 1490,
    seleccionada: false,
    visible: false,
  },
  {
    id: 25,
    tipo: 'mujer',
    nombre: 'Corner',
    url: '/assets/images/modelos/Corner.png',
    urlSvg: 'Corner.svg',
    urlZoom: '/assets/images/zoom/Corner.svg',
    precioIndividual: 1990,
    precioMayorista: 1490,
    seleccionada: false,
    visible: false,
  },
  {
    id: 26,
    tipo: 'mujer',
    nombre: 'Cresi',
    url: '/assets/images/modelos/Cresi.png',
    urlSvg: 'Cresi.svg',
    urlZoom: '/assets/images/zoom/Cresi.svg',
    precioIndividual: 1590,
    precioMayorista: 1190,
    seleccionada: false,
    visible: false,
  },
  // {
  //   id: 27,
  //   tipo: 'mujer',
  //   nombre: 'Valencia',
  //   url: '/assets/images/modelos/Valencia.png',
  //   urlSvg: 'Valencia.svg',
  //   urlZoom: '/assets/images/zoom/Valencia.svg',
  //   precioIndividual: 1990,
  //   precioMayorista: 1490,
  //   seleccionada: false,
  //   visible: false,
  // },
  // {
  //   id: 28,
  //   tipo: 'mujer',
  //   nombre: 'Pixel',
  //   url: '/assets/images/modelos/Pixel.png',
  //   urlSvg: 'Pixel.svg',
  //   urlZoom: '/assets/images/zoom/Pixel',
  //   precioIndividual: 1590,
  //   precioMayorista: 1190,
  //   seleccionada: false,
  //   visible: false,
  // },

]
