export const camisetaModelos = [
  {
    id: 1,
    nombre: 'Classic',
    url: '/assets/images/modelos/Classic.png',
    urlSvg: 'Classic.svg',
    precio: 100,
    seleccionada: false,
    visible: false,
  },
  {
    id: 2,
    nombre: 'City',
    url: '/assets/images/modelos/City.png',
    urlSvg: 'City.svg',
    precio: 200,
    seleccionada: false,
    visible: false,
  },
  {
    id: 3,
    nombre: 'Dortmund',
    url: '/assets/images/modelos/basica3.png',
    urlSvg: 'basica3-dorso.svg',
    precio: 300,
    seleccionada: false,
    visible: false,
  },
  {
    id: 4,
    nombre: 'City',
    url: '/assets/images/intermedias/intermedia1.png',
    urlSvg: 'intermedia1-dorso.svg',
    precio: 400,
    seleccionada: false,
    visible: false,
  },
  {
    id: 5,
    url: '/assets/images/intermedias/intermedia2.png',
    urlSvg: 'intermedia2-dorso.svg',
    seleccionada: false,
    visible: false,
  },
  {
    id: 6,
    url: '/assets/images/intermedias/intermedia3.png',
    urlSvg: 'intermedia3-dorso.svg',
    seleccionada: false,
    visible: false,
  },
  {
    id: 7,
    url: '/assets/images/premium/premium1.png',
    urlSvg: 'premium1-dorso.svg',
    seleccionada: false,
    visible: false,
  },
  {
    id: 8,
    url: '/assets/images/premium/premium2.png',
    urlSvg: 'premium2-dorso.svg',
    seleccionada: false,
    visible: false,
  },
  {
    id: 9,
    url: '/assets/images/premium/premium3.png',
    urlSvg: 'premium3-dorso.svg',
    seleccionada: false,
    visible: false,
  }
]
